trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: Release

jobs:
  - job: BuildCode
    displayName: Build Code
    steps:
    - task: UseDotNet@2
      displayName: 'Get Dotnet 6 SDK'
      timeoutInMinutes: 10
      inputs:
        packageType: 'sdk'
        version: 6.0.306

    - task: UseDotNet@2
      displayName: 'Get Dotnet 7 SDK'
      timeoutInMinutes: 10
      inputs:
        packageType: 'sdk'
        version: 7.0.100

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
        configuration: '$(buildConfiguration)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/src/Useful.Extensions/bin
        artifactName: MyApp

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/tests/Useful.Extensions.Tests/bin
        artifactName: MyAppTests

  - job: TestCode
    displayName: Unit Test Run
    dependsOn: BuildCode
    strategy:
      parallel: 2
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'MyAppTests'
        targetPath: '$(Pipeline.Workspace)'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(Pipeline.Workspace)'
        runInParallel: true
        batchingBasedOnAgentsOption: 'customBatchSize'
        customBatchSizeValue: '100'
        configuration: '$(buildConfiguration)'
        failOnMinTestsNotRun: true
